name: Poll YouTube Channel

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch:         # allow manual runs

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install node-fetch@2 xml2js

      - name: Run monitor
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: node monitor.js
