name: YouTube Video Monitor

on:
  schedule:
    - cron: '0 3 * * *'   # Runs at 3 AM UTC daily
    - cron: '0 15 * * *'  # Runs at 3 PM UTC daily
  workflow_dispatch:       # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run YouTube monitor script
      run: python scripts/youtube_monitor.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: youtube-monitor-results
        path: video_results.json
