name: YouTube Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YouTube Monitor
        run: python scripts/youtube_monitor.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: youtube-monitor-results
          path: video_results.json
